language: nodejs

node_js:
  - 'stable'
  - '8'
  - '6'

matrix:
  fast_finish: true

# TODO: Clean these up once we land on a stable
# way to "remove" puppeteer from the build process
branches:
  only:
    - master
    - chrome-stable
    - puppeteer-1.0.0
    - puppeteer-1.1.1
    - puppeteer-1.2.0
    - puppeteer-1.3.0
    - puppeteer-1.4.0
    - puppeteer-1.5.0

install:
  - npm uninstall typescript --no-save
  - npm uninstall tslint --no-save
  - npm install

script:
  - npm run lint

cache:
  directories:
    - node_modules

git:
  depth: 1
