sudo: required

services:
  - docker

before_install:
  - docker build -t browserless/chrome .
  - docker run -p 4000:4000 -e PORT=4000 --name browserless browserless/chrome

script:
  - docker exec browserless npm test
